name: Publish Website to CPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: Build assets
        run: npm install && npm run build

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: "corporate.vip9.noc401.com"
          username: "jugol@jugol.ctpbd.com"
          password: "t$0^Xbf(pxrx"
          protocol: ftp
          local-dir: dist/
          server-dir: /jugol.ctpbd.com/  # Adjust this if your root folder is different
  